---
    - name: Install dependencies
      apt: name={{ item }} state=present
      with_items:
       - python
       - python-setuptools
       - python-dev
       - build-essential
       - python-pip
       - python-mysqldb
    
    - include: tasks/deploy_db.yml
    - include: tasks/deploy_web.yml